export const parserFillerTerms = [
  "vui lòng",
  "vui long",
  "liệt kê",
  "liet ke",
  "danh sách",
  "danh sach",
  "xem các thiết bị",
  "xem cac thiet bi",
  "các thiết bị",
  "cac thiet bi",
  "thiết bị",
  "thiet bi",
  "trong nhà",
  "trong nha",
  "biết",
  "biet",
  "có",
  "co",
  "gì",
  "gi",
  "thứ",
  "thu",
  "hoạt động",
  "hoat dong",
  "kết nối",
  "ket noi",
  "bao nhiêu",
  "bao nhieu",
  "trạng thái",
  "trang thai",
  "phần trăm",
  "phan tram",
  "độ",
  "do",
  "cho",
  "tui",
  "tôi",
  "toi",
  "giúp",
  "giup",
  "hãy",
  "hay",
  "đi",
  "di",
  "nhé",
  "nhe",
  "list",
  "xem",
  "tìm",
  "tim",
  "kiếm",
  "kiem",
  "các",
  "cac",
  "những",
  "nhung",
  "đang",
  "dang",
  "còn",
  "con",
  "online",
  "offline",
  "không",
  "khong",
  "bật",
  "bat",
  "mở",
  "mo",
  "tắt",
  "tat",
  "set",
  "đặt",
  "dat",
  "tăng",
  "tang",
  "giảm",
  "giam",
  "lên",
  "len",
  "xuống",
  "xuong",
  "chuyển",
  "chuyen"
];

export const genericInventoryQueries = ["nhà", "nha", "toàn bộ", "toan bo", "tất cả", "tat ca"];

export const smartHomeKeywords = [
  "đèn",
  "bóng đèn",
  "máy lạnh",
  "điều hòa",
  "điều hoà",
  "cảm biến",
  "thiết bị",
  "thiet bi",
  "trong nhà",
  "trong nha",
  "list",
  "liệt kê",
  "liet ke",
  "danh sách",
  "danh sach",
  "phòng khách",
  "tiếp khách",
  "phòng ngủ",
  "cửa chính",
  "hoạt động",
  "online",
  "offline",
  "kết nối",
  "bật",
  "tắt",
  "mở",
  "set",
  "đặt",
  "tăng",
  "giảm"
];

export const guardedFallbackIntents = ["out_of_scope", "unsupported"] as const;
export const clarificationIntentTypes = ["clarification_needed", "unsupported"] as const;
export const terminalIntentTypes = ["out_of_scope", "harmful_intent"] as const;
export const heuristicConfidence = {
  harmfulIntent: 0.95,
  outOfScope: 0.9,
  searchDevices: 0.9,
  readDeviceState: 0.84,
  writeDeviceValue: 0.84,
  defaultOutOfScope: 0.65
} as const;
